# grafana/provisioning/datasources/datasources.yml
# Loki pré-configurado para visualização de logs

apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
    version: 1
    editable: false
